# Configuration file for training with FNO model

# Data configuration (placeholder - update with actual data paths)
data:
  train_features_path: "data/train_features.csv"     # Path to training features
  train_targets_path: "data/train_targets.csv"       # Path to training targets
  test_features_path: "data/test_features.csv"       # Path to test features
  test_targets_path: "data/test_targets.csv"         # Path to test targets
  batch_size: 16                                     # Batch size for training
  shuffle: true                                      # Shuffle training data

# Model configuration - FNO model
model:
  name: "fno"                                        # Model name
  parameters:                                        # Model parameters
    in_channels: 1                                   # Number of input channels
    out_channels: 1                                  # Number of output channels
    decoder_layers: 2                                # Number of decoder layers
    decoder_layer_size: 32                           # Number of neurons in decoder layers
    dimension: 2                                     # Model dimensionality (1 or 2)
    latent_channels: 32                              # Latent features size in spectral convolutions
    num_fno_layers: 4                                # Number of spectral convolutional layers
    num_fno_modes: [16, 16]                          # Number of Fourier modes kept in spectral convolutions
    padding: 8                                       # Domain padding for spectral convolutions
    padding_type: "constant"                         # Type of padding for spectral convolutions
    coord_features: true                             # Use coordinate grid as additional feature map

# Training configuration
training:
  epochs: 20                                         # Number of training epochs
  device: "cpu"                                      # Device to use (cpu or cuda)

# Optimizer configuration
optimizer:
  name: "adam"                                       # Optimizer name
  parameters:                                        # Optimizer parameters
    lr: 0.001                                        # Learning rate
    weight_decay: 0.0001                             # Weight decay

# Criterion configuration
criterion:
  name: "mse"                                        # Loss function (mse for regression)
  parameters: {}                                     # Loss function parameters

# Scheduler configuration (optional)
scheduler:
  name: "step"                                       # Scheduler name
  parameters:                                        # Scheduler parameters
    step_size: 10                                    # Step size
    gamma: 0.5                                       # Gamma

# Output configuration
output:
  model_path: "data/fno_model.pth"                   # Path to save trained model
  history_path: "data/fno_training_history.json"     # Path to save training history