# Configuration file for Low-Code Deep Learning Platform

# Data configuration
data:
  train_features_path: "path/to/train_features.csv"  # Path to training features
  train_targets_path: "path/to/train_targets.csv"    # Path to training targets
  test_features_path: "path/to/test_features.csv"    # Path to test features
  test_targets_path: "path/to/test_targets.csv"      # Path to test targets
  batch_size: 32                                     # Batch size for training
  shuffle: true                                      # Shuffle training data

# Model configuration
model:
  name: "ModelTemplate"                              # Model name
  parameters:                                        # Model parameters
    input_size: 784                                  # Input size
    hidden_size: 256                                 # Hidden layer size
    num_classes: 10                                  # Number of classes
    dropout_rate: 0.2                                # Dropout rate

# Training configuration
training:
  epochs: 10                                         # Number of training epochs
  device: "cpu"                                      # Device to use (cpu or cuda)

# Optimizer configuration
optimizer:
  name: "adam"                                       # Optimizer name
  parameters:                                        # Optimizer parameters
    lr: 0.001                                        # Learning rate
    weight_decay: 0.0001                             # Weight decay

# Criterion configuration
criterion:
  name: "cross_entropy"                              # Loss function
  parameters: {}                                     # Loss function parameters

# Scheduler configuration (optional)
scheduler:
  name: "step"                                       # Scheduler name
  parameters:                                        # Scheduler parameters
    step_size: 5                                     # Step size
    gamma: 0.1                                       # Gamma

# Output configuration
output:
  model_path: "trained_model.pth"                   # Path to save trained model
  history_path: "training_history.json"             # Path to save training history