# Test configuration file for Low-Code Deep Learning Platform
# Using the generated complex function dataset

# Data configuration
data:
  train_features_path: "data/train_features.csv"     # Path to training features
  train_targets_path: "data/train_targets.csv"       # Path to training targets
  test_features_path: "data/test_features.csv"       # Path to test features
  test_targets_path: "data/test_targets.csv"         # Path to test targets
  batch_size: 64                                     # Batch size for training
  shuffle: true                                      # Shuffle training data

# Model configuration
model:
  name: "ModelTemplate"                              # Model name
  parameters:                                        # Model parameters
    input_size: 5                                    # Input size (5 features)
    hidden_size: 128                                 # Hidden layer size
    num_classes: 10                                  # Number of classes (0-9)
    dropout_rate: 0.3                                # Dropout rate

# Training configuration
training:
  epochs: 20                                         # Number of training epochs
  device: "cpu"                                      # Device to use (cpu or cuda)

# Optimizer configuration
optimizer:
  name: "adam"                                       # Optimizer name
  parameters:                                        # Optimizer parameters
    lr: 0.001                                        # Learning rate
    weight_decay: 0.0001                             # Weight decay

# Criterion configuration
criterion:
  name: "cross_entropy"                              # Loss function
  parameters: {}                                     # Loss function parameters

# Scheduler configuration (optional)
scheduler:
  name: "step"                                       # Scheduler name
  parameters:                                        # Scheduler parameters
    step_size: 10                                    # Step size
    gamma: 0.1                                       # Gamma

# Output configuration
output:
  model_path: "data/complex_function_model.pth"      # Path to save trained model
  history_path: "data/training_history.json"         # Path to save training history